/* Contas e salvamento na nuvem do RPG Legend. */
var RPG=window.RPG||{};
RPG.Account=(function(){
  var TOKEN_KEY='rpg_legend_account_token',SIGNATURE_KEY='rpg_legend_official_signature_v1',token='',user=null,timer=null,catalog=[],ready=false,cloudAvailable=false;
  function base(){var ws=(window.RPG_MULTIPLAYER_CONFIG&&window.RPG_MULTIPLAYER_CONFIG.serverUrl)||'';return ws.replace(/^wss:/,'https:').replace(/^ws:/,'http:').replace(/\/$/,'');}
  function el(id){return document.getElementById(id);}
  function message(text,error){var profileOpen=!el('profileEditorModal').classList.contains('hidden'),shopOpen=!el('profileShopModal').classList.contains('hidden'),node=el(profileOpen?'profileMessage':(shopOpen?'shopMessage':'accountMessage'));node.textContent=text||'';node.className='account-message'+(error?' error':'');}
  function fillSelect(id,values,labels){var select=el(id),current=select.value;select.innerHTML='';(values||[]).forEach(function(value){var option=document.createElement('option');option.value=value;option.textContent=labels[value]||value;select.appendChild(option);});if((values||[]).includes(current))select.value=current;}
  function renderOwned(){var owned=user&&user.cosmetics||{frames:['none'],colors:['#e8d7a5'],pets:['none']};fillSelect('profileFrame',owned.frames,{none:'Sem moldura',bronze:'Bronze',silver:'Prata',gold:'Ouro',arcane:'Arcana'});fillSelect('profileNameColor',owned.colors,{'#e8d7a5':'Pergaminho','#ffffff':'Branco','#6ee7ff':'Azul','#8cff98':'Verde','#d8a4ff':'Roxo','#ff8f8f':'Vermelho','#ffd166':'Dourado'});fillSelect('profilePet',owned.pets,{none:'Nenhum',chicken:'Galinha (+3% esquiva)',cat:'Gato (+3% crítico)',fox:'Raposa (+2% esquiva e crítico)',owl:'Coruja (5% de chance de poupar mana)',slime:'Slime (+5% cura recebida)'});}
  function render(){
    el('accountGuest').classList.toggle('hidden',!!user);el('accountLogged').classList.toggle('hidden',!user);el('accountName').textContent=user?user.username:'—';
    var menuName=el('menuAccountName'),menuAvatar=el('menuAccountAvatar'),menuFallback=el('menuAccountFallback');if(menuName){menuName.textContent=user?user.username:'Conta';menuName.style.color=user&&user.nameColor?user.nameColor:'';}if(menuAvatar){menuAvatar.classList.toggle('visible',!!(user&&user.avatarUrl));if(user&&user.avatarUrl)menuAvatar.src=user.avatarUrl;}if(menuFallback)menuFallback.classList.toggle('hidden',!!(user&&user.avatarUrl));
    if(!user){if(RPG.Pets)RPG.Pets.render(null);return;}
    renderOwned();
    el('accountName').style.color=user.nameColor||'#e8d7a5';
    var avatar=el('accountAvatar');avatar.classList.toggle('hidden',!user.avatarUrl);if(user.avatarUrl)avatar.src=user.avatarUrl;
    el('profileAvatarUrl').value=user.avatarUrl&&user.avatarUrl.indexOf('data:image/')!==0?user.avatarUrl:'';el('profileFrame').value=user.frame||'none';el('profileNameColor').value=user.nameColor||'#e8d7a5';el('profilePet').value=user.pet||'none';
    el('profileAccountEmail').value=user.email||'';el('accountEmailStatus').textContent=user.email?(user.emailVerified?'✅ E-mail confirmado: ':'⚠ E-mail ainda não confirmado: ')+user.email:'Esta conta antiga ainda não possui e-mail.';el('resendVerificationBtn').classList.toggle('hidden',!user.email||user.emailVerified);
    el('accountLogged').setAttribute('data-frame',user.frame||'none');
    if(RPG.Pets)RPG.Pets.render(user);
  }
  async function request(path,options){options=options||{};options.headers=Object.assign({'Content-Type':'application/json'},options.headers||{});if(token)options.headers.Authorization='Bearer '+token;var response=await fetch(base()+path,options),data=await response.json().catch(function(){return {};});if(!response.ok)throw new Error(data.error||'Não foi possível conectar ao servidor.');return data;}
  function announceReady(){ready=true;document.dispatchEvent(new CustomEvent('rpg-account-ready',{detail:{user:user,cloudAvailable:cloudAvailable}}));}
  function openAccount(text){el('accountModal').classList.remove('hidden');if(text)message(text,true);}
  function credentials(){return {username:(el('accountUsername').value||'').trim(),email:(el('accountEmail').value||'').trim(),password:el('accountPassword').value||''};}
  async function syncCloud(){var data=await request('/api/save');if(data.save){localStorage.setItem(RPG.Save.KEY,JSON.stringify(data.save));if(data.signature)localStorage.setItem(SIGNATURE_KEY,data.signature);RPG.Save.markOfficial();cloudAvailable=true;message('Progresso oficial carregado da nuvem.');return true;}cloudAvailable=false;if(RPG.Save.hasSave()&&!RPG.Save.isImportedBackup()){if(window.confirm('Encontramos um progresso antigo neste navegador. Deseja migrá-lo agora para esta conta?'))return upload(false);message('A migração foi adiada. O progresso ficará bloqueado até ser enviado para a nuvem.',true);}else if(RPG.Save.isImportedBackup())message('Backups importados não podem ser migrados para o jogo online.',true);return false;}
  async function enter(mode){try{ready=false;message(mode==='register'?'Criando conta…':'Entrando…');var data=await request('/api/account/'+mode,{method:'POST',body:JSON.stringify(credentials())});token=data.token;user=data.user;localStorage.setItem(TOKEN_KEY,token);el('accountPassword').value='';render();await syncCloud();await loadCatalog();if(!cloudAvailable)message('Conta conectada. Crie um personagem ou migre seu progresso para começar.');announceReady();}catch(e){ready=true;message(e.message,true);announceReady();}}
  async function refresh(){ready=false;token=localStorage.getItem(TOKEN_KEY)||'';if(!token){user=null;cloudAvailable=false;render();announceReady();return;}try{var data=await request('/api/account/me');user=data.user;render();await syncCloud();await loadCatalog();}catch(e){token='';user=null;cloudAvailable=false;localStorage.removeItem(TOKEN_KEY);render();message('Entre novamente para acessar seu progresso na nuvem.',true);}announceReady();}
  function renderShop(owned){var list=el('profileShopList');list.innerHTML='';catalog.forEach(function(item){var bucket=item.type==='frame'?'frames':(item.type==='color'?'colors':'pets'),has=(owned[bucket]||[]).includes(item.value),card=document.createElement('div');card.className='item-card';var title=document.createElement('b');title.textContent=item.icon+' '+item.name;var price=document.createElement('div');price.textContent=has?'Desbloqueado':item.price+' ouro';var button=document.createElement('button');button.className='rune-btn small';button.textContent=has?'Possuído':'Comprar';button.disabled=has;button.onclick=function(){purchase(item.id);};card.appendChild(title);card.appendChild(price);card.appendChild(button);list.appendChild(card);});}
  async function loadCatalog(){if(!user)return;var data=await request('/api/account/profile/catalog');catalog=data.catalog||[];renderShop(data.owned||user.cosmetics||{});}
  async function purchase(id){try{message('Confirmando compra…');var data=await request('/api/account/profile/purchase',{method:'POST',body:JSON.stringify({id:id})});user=data.user;if(data.save){localStorage.setItem(RPG.Save.KEY,JSON.stringify(data.save));if(RPG.state&&RPG.state.hero)RPG.state.hero.gold=data.save.hero.gold;}if(data.signature)localStorage.setItem(SIGNATURE_KEY,data.signature);RPG.Save.markOfficial();render();await loadCatalog();if(RPG.UI&&RPG.UI.renderHero)RPG.UI.renderHero();message(data.item.name+' foi desbloqueado.');}catch(e){message(e.message,true);}}
  async function compressPhoto(file){if(!file)return '';if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>5000000)throw new Error('Escolha uma foto PNG, JPG ou WebP de até 5 MB.');var bitmap=await createImageBitmap(file),size=Math.min(256,Math.max(bitmap.width,bitmap.height)),scale=Math.min(size/bitmap.width,size/bitmap.height),canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;var ctx=canvas.getContext('2d');ctx.fillStyle='#111';ctx.fillRect(0,0,size,size);ctx.drawImage(bitmap,(size-bitmap.width*scale)/2,(size-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();var result=canvas.toDataURL('image/webp',.82);if(result.length>400000)result=canvas.toDataURL('image/jpeg',.68);if(result.length>400000)throw new Error('Não foi possível reduzir essa foto. Escolha uma imagem menor.');return result;}
  async function saveProfile(){try{message('Salvando perfil…');var file=el('profileAvatarFile').files&&el('profileAvatarFile').files[0],avatarUrl=file?await compressPhoto(file):((el('profileAvatarUrl').value||'').trim()||user.avatarUrl||'');var data=await request('/api/account/profile',{method:'PUT',body:JSON.stringify({avatarUrl:avatarUrl,frame:el('profileFrame').value,nameColor:el('profileNameColor').value,pet:el('profilePet').value})});user=data.user;el('profileAvatarFile').value='';render();message('Perfil atualizado.');}catch(e){message(e.message,true);}}
  async function saveEmail(){try{var email=(el('profileAccountEmail').value||'').trim(),password=el('profileEmailPassword').value||'';var data=await request('/api/account/email',{method:'PUT',body:JSON.stringify({email:email,password:password})});user=data.user;el('profileEmailPassword').value='';render();message('E-mail salvo. Enviamos um link de confirmação.');}catch(e){message(e.message,true);}}
  async function resendVerification(){try{await request('/api/account/resend-verification',{method:'POST'});message('Novo link de confirmação enviado.');}catch(e){message(e.message,true);}}
  async function forgotPassword(){var email=window.prompt('Digite o e-mail da conta:');if(!email)return;try{var data=await request('/api/account/request-password-reset',{method:'POST',body:JSON.stringify({email:email})});message(data.message||'Confira seu e-mail.');el('accountModal').classList.remove('hidden');}catch(e){message(e.message,true);}}
  async function handleEmailLink(){var query=new URLSearchParams(location.search),verify=query.get('verify'),reset=query.get('reset');if(!verify&&!reset)return;el('accountModal').classList.remove('hidden');try{if(verify){await request('/api/account/verify-email',{method:'POST',body:JSON.stringify({token:verify})});message('E-mail confirmado com sucesso. Entre na conta.');}else{var password=window.prompt('Crie uma nova senha com pelo menos 8 caracteres:');if(!password)return;var confirmation=window.prompt('Digite a nova senha novamente:');if(password!==confirmation)throw new Error('As senhas não coincidem.');await request('/api/account/reset-password',{method:'POST',body:JSON.stringify({token:reset,password:password})});localStorage.removeItem(TOKEN_KEY);token='';user=null;message('Senha alterada. Entre novamente.');}history.replaceState({},document.title,location.pathname+location.hash);}catch(e){message(e.message,true);}}
  async function upload(silent){if(!user||!RPG.Save.hasSave())return false;if(RPG.Save.isImportedBackup()){if(!silent)message('Backups importados não podem substituir o progresso oficial.',true);return false;}try{var data=RPG.Save.load();if(data&&data.hero){data.hero.name=user.username;if(RPG.state&&RPG.state.hero)RPG.state.hero.name=user.username;localStorage.setItem(RPG.Save.KEY,JSON.stringify(data));}var saved=await request('/api/save',{method:'PUT',body:JSON.stringify({save:data,source:'game',baseSignature:localStorage.getItem(SIGNATURE_KEY)||''})});if(saved.signature)localStorage.setItem(SIGNATURE_KEY,saved.signature);cloudAvailable=true;document.dispatchEvent(new CustomEvent('rpg-cloud-save-ready'));if(!silent)message('Progresso oficial assinado e salvo na nuvem.');return true;}catch(e){if(!silent)message(e.message,true);return false;}}
  async function download(){try{var data=await request('/api/save');if(!data.save){message('Esta conta ainda não possui progresso na nuvem.',true);return;}if(!window.confirm('Carregar o progresso da nuvem substituirá o progresso deste navegador. Continuar?'))return;localStorage.setItem(RPG.Save.KEY,JSON.stringify(data.save));if(data.signature)localStorage.setItem(SIGNATURE_KEY,data.signature);RPG.Save.markOfficial();message('Progresso oficial recuperado. Recarregando…');setTimeout(function(){window.location.reload();},500);}catch(e){message(e.message,true);}}
  async function restorePrevious(){try{var data=await request('/api/save/history');if(!data.versions||!data.versions.length){message('Ainda não existe uma versão anterior na nuvem.',true);return;}var version=data.versions[0],when=new Date(version.createdAt).toLocaleString('pt-BR');if(!window.confirm('Restaurar a versão da nuvem salva em '+when+'? O save atual também ficará guardado no histórico.'))return;var restored=await request('/api/save/restore',{method:'POST',body:JSON.stringify({id:version.id})});localStorage.setItem(RPG.Save.KEY,JSON.stringify(restored.save));if(restored.signature)localStorage.setItem(SIGNATURE_KEY,restored.signature);RPG.Save.markOfficial();message('Versão anterior restaurada. Recarregando…');setTimeout(function(){window.location.reload();},500);}catch(e){message(e.message,true);}}
  function scheduleCloudSave(){if(!user)return;clearTimeout(timer);timer=setTimeout(function(){upload(true);},2500);}
  async function verifyOfficial(){if(!user)return false;if(!RPG.Save.hasSave())return true;var signature=localStorage.getItem(SIGNATURE_KEY)||'';if(!signature)return false;try{var result=await request('/api/save/verify',{method:'POST',body:JSON.stringify({save:RPG.Save.load(),signature:signature})});return !!result.valid;}catch(e){return false;}}
  async function resetCloud(){try{await request('/api/save/reset',{method:'POST'});cloudAvailable=false;localStorage.removeItem(SIGNATURE_KEY);RPG.Save.clear();document.dispatchEvent(new CustomEvent('rpg-account-ready',{detail:{user:user,cloudAvailable:false}}));return true;}catch(e){message(e.message,true);return false;}}
  async function logout(){try{await request('/api/account/logout',{method:'POST'});}catch(e){}token='';user=null;cloudAvailable=false;localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(SIGNATURE_KEY);RPG.Save.clear();window.location.reload();}
  async function init(){
    el('btnAccount').onclick=function(){el('accountModal').classList.remove('hidden');refresh();};el('closeAccountBtn').onclick=function(){el('accountModal').classList.add('hidden');};
    el('openProfileEditorBtn').onclick=function(){el('accountModal').classList.add('hidden');el('profileEditorModal').classList.remove('hidden');render();};el('closeProfileEditorBtn').onclick=function(){el('profileEditorModal').classList.add('hidden');};
    var shopButton=el('btnProfileShop');if(shopButton)shopButton.onclick=function(){refresh().then(function(){if(!user){el('accountModal').classList.remove('hidden');message('Entre ou crie uma conta para acessar a loja.',true);return;}el('profileShopModal').classList.remove('hidden');loadCatalog();});};el('closeProfileShopBtn').onclick=function(){el('profileShopModal').classList.add('hidden');};
    el('accountLoginBtn').onclick=function(){enter('login');};el('accountRegisterBtn').onclick=function(){enter('register');};el('forgotPasswordBtn').onclick=forgotPassword;el('profileSaveBtn').onclick=saveProfile;el('accountEmailSaveBtn').onclick=saveEmail;el('resendVerificationBtn').onclick=resendVerification;el('cloudSaveBtn').onclick=function(){upload(false);};el('cloudLoadBtn').onclick=download;el('cloudRestoreBtn').onclick=restorePrevious;el('accountLogoutBtn').onclick=logout;await handleEmailLink();refresh();
  }
  document.addEventListener('DOMContentLoaded',init);
  return {scheduleCloudSave:scheduleCloudSave,upload:upload,verifyOfficial:verifyOfficial,resetCloud:resetCloud,currentUser:function(){return user;},isReady:function(){return ready;},hasCloudSave:function(){return cloudAvailable;},open:openAccount};
})();
