/* Contas e salvamento na nuvem do RPG Legend. */
var RPG=window.RPG||{};
RPG.Account=(function(){
  var TOKEN_KEY='rpg_legend_account_token',SIGNATURE_KEY='rpg_legend_official_signature_v1',token='',user=null,timer=null;
  function base(){var ws=(window.RPG_MULTIPLAYER_CONFIG&&window.RPG_MULTIPLAYER_CONFIG.serverUrl)||'';return ws.replace(/^wss:/,'https:').replace(/^ws:/,'http:').replace(/\/$/,'');}
  function el(id){return document.getElementById(id);}
  function message(text,error){var node=el('accountMessage');node.textContent=text||'';node.className='account-message'+(error?' error':'');}
  function render(){el('accountGuest').classList.toggle('hidden',!!user);el('accountLogged').classList.toggle('hidden',!user);el('accountName').textContent=user?user.username:'—';el('btnAccount').textContent=user?'👤 '+user.username:'👤 Conta';}
  async function request(path,options){options=options||{};options.headers=Object.assign({'Content-Type':'application/json'},options.headers||{});if(token)options.headers.Authorization='Bearer '+token;var response=await fetch(base()+path,options),data=await response.json().catch(function(){return {};});if(!response.ok)throw new Error(data.error||'Não foi possível conectar ao servidor.');return data;}
  function credentials(){return {username:(el('accountUsername').value||'').trim(),password:el('accountPassword').value||''};}
  async function enter(mode){try{message(mode==='register'?'Criando conta…':'Entrando…');var data=await request('/api/account/'+mode,{method:'POST',body:JSON.stringify(credentials())});token=data.token;user=data.user;localStorage.setItem(TOKEN_KEY,token);el('accountPassword').value='';render();message('Conta conectada. Seu progresso pode ser salvo na nuvem.');if(mode==='register'&&RPG.Save.hasSave())upload();}catch(e){message(e.message,true);}}
  async function refresh(){token=localStorage.getItem(TOKEN_KEY)||'';if(!token){render();return;}try{var data=await request('/api/account/me');user=data.user;}catch(e){token='';user=null;localStorage.removeItem(TOKEN_KEY);}render();}
  async function upload(silent){if(!user||!RPG.Save.hasSave())return false;if(RPG.Save.isImportedBackup()){if(!silent)message('Este progresso veio de um arquivo editável e está no modo offline. Carregue o save oficial da nuvem para voltar ao modo online.',true);return false;}try{var data=RPG.Save.load(),saved=await request('/api/save',{method:'PUT',body:JSON.stringify({save:data,source:'game',baseSignature:localStorage.getItem(SIGNATURE_KEY)||''})});if(saved.signature)localStorage.setItem(SIGNATURE_KEY,saved.signature);if(!silent)message('Progresso oficial assinado e salvo na nuvem.');return true;}catch(e){if(!silent)message(e.message,true);return false;}}
  async function download(){try{var data=await request('/api/save');if(!data.save){message('Esta conta ainda não possui progresso na nuvem.',true);return;}if(!window.confirm('Carregar o progresso da nuvem substituirá o progresso deste navegador. Continuar?'))return;localStorage.setItem(RPG.Save.KEY,JSON.stringify(data.save));if(data.signature)localStorage.setItem(SIGNATURE_KEY,data.signature);RPG.Save.markOfficial();message('Progresso oficial recuperado. Recarregando…');setTimeout(function(){window.location.reload();},500);}catch(e){message(e.message,true);}}
  async function restorePrevious(){try{var data=await request('/api/save/history');if(!data.versions||!data.versions.length){message('Ainda não existe uma versão anterior na nuvem.',true);return;}var version=data.versions[0],when=new Date(version.createdAt).toLocaleString('pt-BR');if(!window.confirm('Restaurar a versão da nuvem salva em '+when+'? O save atual também ficará guardado no histórico.'))return;var restored=await request('/api/save/restore',{method:'POST',body:JSON.stringify({id:version.id})});localStorage.setItem(RPG.Save.KEY,JSON.stringify(restored.save));if(restored.signature)localStorage.setItem(SIGNATURE_KEY,restored.signature);RPG.Save.markOfficial();message('Versão anterior restaurada. Recarregando…');setTimeout(function(){window.location.reload();},500);}catch(e){message(e.message,true);}}
  function scheduleCloudSave(){if(!user)return;clearTimeout(timer);timer=setTimeout(function(){upload(true);},2500);}
  async function verifyOfficial(){if(!user)return false;if(!RPG.Save.hasSave())return true;var signature=localStorage.getItem(SIGNATURE_KEY)||'';if(!signature)return false;try{var result=await request('/api/save/verify',{method:'POST',body:JSON.stringify({save:RPG.Save.load(),signature:signature})});return !!result.valid;}catch(e){return false;}}
  async function logout(){try{await request('/api/account/logout',{method:'POST'});}catch(e){}token='';user=null;localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(SIGNATURE_KEY);render();message('Você saiu da conta. O progresso local continua neste navegador.');}
  function init(){
    el('btnAccount').onclick=function(){el('accountModal').classList.remove('hidden');refresh();};el('closeAccountBtn').onclick=function(){el('accountModal').classList.add('hidden');};
    el('accountLoginBtn').onclick=function(){enter('login');};el('accountRegisterBtn').onclick=function(){enter('register');};el('cloudSaveBtn').onclick=function(){upload(false);};el('cloudLoadBtn').onclick=download;el('cloudRestoreBtn').onclick=restorePrevious;el('accountLogoutBtn').onclick=logout;refresh();
  }
  document.addEventListener('DOMContentLoaded',init);
  return {scheduleCloudSave:scheduleCloudSave,upload:upload,verifyOfficial:verifyOfficial,currentUser:function(){return user;}};
})();
